### ISSUE TITLE
Company info

### ISSUE THREAD

**Issue by destroytoday** [zmoazeni/harvested#87]
Is it possible to get the current user's company info through Harvested?—the `who_am_i` method seems to ignore the company data returned from that endpoint.

**Comment by jvdp** [comment]
Doesn't seem to be possible currently, PR's are always welcome though.

**Comment by zmoazeni** [comment]
Just merged https://github.com/zmoazeni/harvested/pull/90 and will release v4.0 soon. That'll be included in the `who_am_i` now.
