### ISSUE TITLE
Unexpected results from filtering .all

### ISSUE THREAD

**Issue by irons** [zmoazeni/harvested#91]
I'm hoping I'm missing something basic about the example given in the readme, which asserts "You can pass in any hash of query attributes you wish as per the Harvest API page.", giving as an example:

`harvest.projects.all(nil, :client => 12345)`

This works for `:client`, but seemingly not for other attributes:

```
harvest.projects.all # correctly returns all of our projects
harvest.projects.all(nil, :client => 1914731)  # correctly returns 2 items

harvest.projects.all(nil, :billable => false) # incorrectly returns all projects, should return fewer
harvest.projects.all(nil, :active => false) # incorrectly returns all projects, should return way fewer
harvest.projects.all(nil, :name => "Holiday")  # incorrectly returns all projects, should return 1
harvest.projects.all(nil, :name => "Total rubbish")  # incorrectly returns all projects, should return 0
```
I'm verifying my assumptions about API data against the XML returned by a naked POST API call for /`projects`, while signed in as the same user in the ruby script. The only thing they agree on is the total count of projects. I also see expected results when I dump the objects returned by an `.all` method — that is, some projects are and aren't billable, are and aren't active, etc. Similar results when I try to filter for clients, and for people/users.

Am I overlooking a syntactical wrinkle? Thanks.

**Comment by zmoazeni** [comment]
Right now you can only filter projects by `client` and `updated_since` per https://github.com/harvesthq/api/blob/master/Sections/Projects.md#show-all-projects
