### ISSUE TITLE
csv_line_items not returned for invoice(s)

### ISSUE THREAD

**Issue by joewarner** [zmoazeni/harvested#93]
If I send the command `curl -u <user>:<pass> -XGET -i 'http://MYACCOUNT.harvestapp.com/invoices/10259606' -L -H "Accept: application/json"` then I get  csv_line_items back as a field, but this field doesn't seem to be present when I make the same call via harvested, e.g. `inv = harvest.invoices.find(10259606)`.

Is the code for exposing this field incomplete or is there a bug?

**Comment by spovich** [comment]
@joewarner We ran into this in testing, but realized that the issue is the difference between calling  `harvest.invoices` and `harvest.invoices.find(xxx)`.  The former does *NOT* include the `csv_line_items` details where the latter does include `csv_line_items`.

**Comment by zmoazeni** [comment]
Thanks for helping debug @spovich!
