### ISSUE TITLE
External Reference URL

### ISSUE THREAD

**Issue by pedstrom** [zmoazeni/harvested#97]
Is there a way to pull the External Reference URL on time entries out of Harvest? I see this column in the admin export of all time entries, but not in the TimeEntry object.

<img width="835" alt="screen shot 2017-08-17 at 7 30 08 am" src="https://user-images.githubusercontent.com/56623/29419615-2cc12168-8335-11e7-9432-26e59bcd5c69.png">

**Comment by pedstrom** [comment]
I'm using `time_entries = harvest.reports.time_by_user(...)` and just found out from Harvest support that the reports API does not have the external reference info. If I pull the individual time `t = harvest.time.find(1234)` then I get a `external_ref` object. Woot!

**Comment by zmoazeni** [comment]
Awesome!
